### ISSUE TITLE
Provision fails for clean install

### ISSUE THREAD

**Issue by mikkelbreum** [wpengine/hgv#250]
On Mac OSX  with vmware provider.

_installing from scratch:_

    git clone https://github.com/wpengine/hgv.git
    cd hgv
    npm install
    vagrant up --provider=vmware_fusion

the VM boots up, and the provisioning starts. The provisioning fails when it comes to

    TASK: [admin | Configure phpMyAdmin]

I have retried installing and provisioning the vagrant 4 times, but I get this error each time.
This is the final output:

    ==> hgv: TASK: [admin | Download phpMyAdmin] *******************************************
    ==> hgv: changed: [127.0.0.1]
    ==> hgv:
    ==> hgv: TASK: [admin | Extract phpMyAdmin] ********************************************
    ==> hgv: changed: [127.0.0.1]
    ==> hgv:
    ==> hgv: TASK: [admin | Sync phpMyAdmin] ***********************************************
    ==> hgv: changed: [127.0.0.1 -> 127.0.0.1]
    ==> hgv:
    ==> hgv: TASK: [admin | Configure phpMyAdmin] ******************************************
    ==> hgv: failed: [127.0.0.1] => {"failed": true, "parsed": false}
    ==> hgv: BECOME-SUCCESS-bhrdryiazgiurutjeokxjszyprjmwefo
    ==> hgv: Traceback (most recent call last):
    ==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1443553096.84-136657738858744/copy", line 1933, in <module>
    ==> hgv:     main()
    ==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1443553096.84-136657738858744/copy", line 300, in main
    ==> hgv:     module.atomic_move(src, dest)
    ==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1443553096.84-136657738858744/copy", line 1728, in atomic_move
    ==> hgv:     os.chown(dest, os.getuid(), os.getgid())
    ==> hgv: OSError: [Errno 1] Operation not permitted: '/nas/wp/www/sites/admin/phpmyadmin /config.inc.php'
    ==> hgv: Exception OSError: (2, 'No such file or directory', '/nas/wp/www/sites/admin/phpmyadmin/.ansible_tmp5NT4KZconfig.inc.php') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7f0142408390>> ignored
    ==> hgv:
    ==> hgv:
    ==> hgv: FATAL: all hosts have already failed -- aborting
    ==> hgv:
    ==> hgv: PLAY RECAP ********************************************************************
    ==> hgv:            to retry, use: --limit @/root/playbook.retry
    ==> hgv: 127.0.0.1                  : ok=74   changed=8    unreachable=0    failed=1
    The SSH command responded with a non-zero exit status. Vagrant
    assumes that this means the command failed. The output for this command
    should be in the log above. Please read the output to determine what
    went wrong.

**Comment by andrew40** [comment]
I also do a new full provision but any custom.yaml files are read but the ****.test domains do not resolve at all. Have tried reload, re provision etc but cannot get the custom.yaml domains to work at all.

**Comment by jwall** [comment]
I am experiencing the same behavior.

**Comment by anthonysexton** [comment]
So am I although mine seems to fail at a different point: 

==> hgv: TASK: [admin | Setup phpinfo.php] ********************************************* 
==> hgv: failed: [127.0.0.1] => {"failed": true, "parsed": false}
==> hgv: BECOME-SUCCESS-obiqxcsgooqdfwnkwgcdjuiupbapiwcw
==> hgv: Traceback (most recent call last):
==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1446454266.02-83257668081472/copy", line 1933, in <module>
==> hgv:     main()
==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1446454266.02-83257668081472/copy", line 300, in main
==> hgv:     module.atomic_move(src, dest)
==> hgv:   File "/root/.ansible/tmp/ansible-tmp-1446454266.02-83257668081472/copy", line 1728, in atomic_move
==> hgv:     os.chown(dest, os.getuid(), os.getgid())
==> hgv: OSError: [Errno 1] Operation not permitted: '/nas/wp/www/sites/admin/phpinfo.php'
==> hgv: Exception OSError: (2, 'No such file or directory', '/nas/wp/www/sites/admin/.ansible_tmp9WQB0_phpinfo.php') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7f899594c390>> ignored

**Comment by pablinos** [comment]
Hi,
Not sure if you're still looking for a solution to this, but it turns out that it's to do with file permissions on that chown statement. I'm also using hgv, so I've hacked the hgv-init script to check out ansible instead of using the ubuntu package, and then I apply a patch to ignore permissions errors on that statement.

Pretty hacky I know, but it works!

I've got the patches but I can't seem to upload them. I suppose I could fork hgv if that would help?
